### PR TITLE
Improvement of MLPDecoder 

### PR DESCRIPTION
**Pull request by atamazian**
Improvement of MLPDecoder:
- added ability to change number of layers
- parameters are set in yaml file

### CODE REVIEW

**Comment by tubo213** [comment]
@atamazian 

Thanks for improving the code.

It is a minor detail, but I would like to see it implemented using [nn.ModuleList](https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html) instead of nn.Sequential(**mlp).

**Comment by atamazian** [comment]
Is it OK now?

**Comment by tubo213** [comment]
@atamazian 
LGTM!

**Comment by tubo213** [comment]
@atamazian 

Please comment to [Disscussion](https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2530545) that you have improved MLPDecoder, as exchanges on github may fall under the category of private sharing.

**Comment by atamazian** [comment]
Done. Thanks for the advice!

**Pull request merged**
